### ISSUE TITLE
As first time, running gimme-aws-creds returns a error 

### ISSUE THREAD

**Issue by ogarciatn** [Nike-Inc/gimme-aws-creds#107]
After use the **gimme-aws-creds** as first time,

complete the verification with Okta:
```
Multi-factor Authentication required.
Okta Verify App: SmartPhone_Android: Moto E (4) Plus selected
Okta Verify push sent...
done
```
 And pick a role:
```
Pick a role any role:
[0] arn:aws:iam::<ID>:role/<ROLE_NAME>
[1] arn:aws:iam::<ID>:role/<ROLE_NAME>
Selection: 1
```
returns this error:
```Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 453, in run
    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, config.aws_default_duration)
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 135, in _get_sts_creds
    client = boto3.client('sts')
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 80, in _get_default_session
    setup_default_session()
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 34, in setup_default_session
    DEFAULT_SESSION = Session(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 679, in get_component
    return self._components.get_component(name)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 902, in get_component
    self._components[name] = factory()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 150, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 233, in get_config_variable
    logical_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/configprovider.py", line 226, in get_config_variable
    return provider.provide()
  File "/usr/local/lib/python3.7/site-packages/botocore/configprovider.py", line 323, in provide
    value = provider.provide()
  File "/usr/local/lib/python3.7/site-packages/botocore/configprovider.py", line 382, in provide
    config = self._session.get_scoped_config()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 334, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (<PROFILE_NAME>) could not be found
```
My solution was just create in 
`~/.aws/credentials` a new **PROFILE_NAME**  (_empty_ ) like: 
```
[default]
aws_access_key_id = blabla
aws_secret_access_key = blabla

[PROFILE_NAME]
```
And works! 😄 But I think should be something that **gimme-aws-creds** should do or returns a better exception. 👍 

Its retaliated with #93

**Comment by Sector95** [comment]
Yup this is a big one, ran into it myself just last week when setting up a new employee.  We'll get a patch out.

**Comment by Sector95** [comment]
This should no longer be a problem in the newer releases.  Thanks!

**Comment by Mizaro** [comment]
Got the same problem and fixed it with the same solution as written here. 
Installed version is 2.3.5. (Fresh install on Mac Pro M1 using brew)

**Comment by sakthimaan** [comment]
> This should no longer be a problem in the newer releases. Thanks!

Getting this issue in 2.4.0

**Comment by eponymz** [comment]
Still getting this issue in 2.7.2
