### ISSUE TITLE
Running gimme-aws-creds gives "Invalid endpoint" error

### ISSUE THREAD

**Issue by feixie1980** [Nike-Inc/gimme-aws-creds#128]
I am using macOS Sierra 10.12.6, with python3 3.7.4.

The configuration and device registration run successfully: 
1. ```gimme-aws-creds --configure``` 
2. ```gimme-aws-creds --register_device```

However, I run into an error when executing:

3. ```gimme-aws-creds```.  

I have attached the exception stacks below.  Does anyone know what could have cause the problem?

```
gimme-aws-creds

Using password from keyring for username
Detected single role: arn:aws:iam::231324122:role/okta-br-tl
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 465, in run
    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, config.aws_default_duration)
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 136, in _get_sts_creds
    client = boto3.client('sts')
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 839, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 85, in get_client_args
    client_cert=new_config.client_cert)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 261, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://sts..amazonaws.com
```
Thank you in advance!

**Comment by casey-robertson** [comment]
Can you share your config file?
