### ISSUE TITLE
UnboundLocalError: local variable 'aws_creds' referenced before assignment

### ISSUE THREAD

**Issue by acabrera-rms** [Nike-Inc/gimme-aws-creds#132]
Pip package and Docker image not working with python 3.7.X in Mac OS X 10.12.6
## Expected Behavior

❯ gimme-aws-creds --profile stg-env
credentials are written to credentials file or printed to stdout 

## Current Behavior

❯ gimme-aws-creds --profile stg-env
Password for me@me.com:
Pick a role:
[0] arn:aws:iam::01978321206:role/Fullaccess
[1] arn:aws:iam::01978321206:role/EngineerRole
[2] arn:aws:iam::01978321206:role/AdminRole
Selection: 2
writing role arn:aws:iam::01978321206:role/AdminRole to /root/.aws/credentials
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 4, in <module>
    __import__('pkg_resources').run_script('gimme-aws-creds==1.1.8', 'gimme-aws-creds')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds-1.1.8-py3.7.egg/EGG-INFO/scripts/gimme-aws-creds", line 17, in <module>
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds-1.1.8-py3.7.egg/gimme_aws_creds/main.py", line 492, in run
UnboundLocalError: local variable 'aws_creds' referenced before assignment
## Steps to Reproduce (for bugs)

1. clone repo
2. build docker file
3. create alias
4. get creds

## Your Environment

* App Version used: latest
* Environment name and version: python 3.7.X
* Operating System and version: OS X 10.12.6

**Comment by acabrera-rms** [comment]
nvm, somehow it works now.
