### ISSUE TITLE
KeyError: 'location'

### ISSUE THREAD

**Issue by elice02** [Nike-Inc/gimme-aws-creds#135]
Another problem. Any ideas about this one?

aaa@aaa-Laptop2018:~$ gimme-aws-creds --profile aaaa
Please enter password for encrypted keyring:
Traceback (most recent call last):
  File "/home/aaa/.local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/home/aaa/.local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 444, in run
    scopes=['openid']
  File "/home/aaa/.local/lib/python3.6/site-packages/gimme_aws_creds/okta.py", line 222, in auth_oauth
    url_parse_results = urlparse(response.headers['Location'])
  File "/home/aaa/.local/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by TimAtAdaptive** [comment]
It means the  `okta_auth_server` didn't return a valid response (in my case the url was wrong and it returned a 404 not found response)
