### ISSUE TITLE
gimme-aws-creds give Did not receive SAML Response after successful authentication

### ISSUE THREAD

**Issue by rameshsubramanian87** [Nike-Inc/gimme-aws-creds#137]
$ gimme-aws-creds
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 454, in run
    saml_data = okta.get_saml_response(aws_app['links']['appLink'])
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/okta.py", line 459, in get_saml_response
    'Did not receive SAML Response after successful authentication [' + url + ']')
RuntimeError: Did not receive SAML Response after successful authentication

**Comment by Sector95** [comment]
Not enough information here to be able to understand the problem. As a start, can you post your **censored** configuration file?

**Comment by pprzetacznik** [comment]
Have the same issue.

**Comment by gangakrishh** [comment]
I was getting this
my version is gimme-aws-creds 2.2.0
`Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 447, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 738, in _run
    for data in self.iter_selected_aws_credentials():
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 714, in iter_selected_aws_credentials
    for role in self.aws_selected_roles:
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 632, in aws_selected_roles
    selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 623, in aws_roles
    self.saml_data['SAMLResponse'],
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 614, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/okta.py", line 702, in get_saml_response
    'Did not receive SAML Response after successful authentication [' + url + ']')
RuntimeError: Did not receive SAML Response after successful authentication`

**Comment by gadupushailaja** [comment]
@rameshsubramanian87  Does this issue resolved for you? If so, can you tell what did you do to resolve it?

**Comment by apsylone** [comment]
Same problem here.
