### ISSUE TITLE
Did not receive SAML response after successful authentication

### ISSUE THREAD

**Issue by jshill103** [Nike-Inc/gimme-aws-creds#151]
I selected the Okta Verify app: smartphone_iphone option to get creds, received the push on my apple watch and got an error. 

user:Repos user$ gimme-aws-creds
Using password from keyring for user
Multi-factor Authentication required.
Pick a factor:
[0] Okta Verify App: SmartPhone_IPhone: Jared’s iPhone
[1] sms: +1 XXX-XXX-XXXX
[2] token:software:totp( GOOGLE ) : user@work.com
[3] token:software:totp( OKTA ) : user@work.com
Selection: 0
Okta Verify push sent...
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 447, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 738, in _run
    for data in self.iter_selected_aws_credentials():
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 714, in iter_selected_aws_credentials
    for role in self.aws_selected_roles:
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 632, in aws_selected_roles
    selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 623, in aws_roles
    self.saml_data['SAMLResponse'],
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 614, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/okta.py", line 605, in get_saml_response
    'Did not receive SAML Response after successful authentication [' + url + ']')
RuntimeError: Did not receive SAML Response after successful authentication

## Expected Behavior

Expecting to get creds

## Current Behavior

currently fails to a thrown error

## Possible Solution

It might be that accepting from apple watch doesn't send back SAML

## Steps to Reproduce (for bugs)

1. gimme-aws-creds --register_device
2. gimme-aws-creds --configure
3. gimme-aws-creds select 0
4. accept okta verify on apple watch

## Your Environment

* App Version used:
* Environment name and version:
* Operating System and version:

**Comment by jshill103** [comment]
I was able to get it to work with selecting the sms option to my phone but not through my apple watch

**Comment by gadupushailaja** [comment]
I am getting the same error, in my case it is push notification to my phone. I get the above error and then the push notification sent to my phone. Can someone help here please.
