### ISSUE TITLE
ModuleNotFoundError: No module named 'keyring.util.escape'

### ISSUE THREAD

**Issue by gg-chrisd** [Nike-Inc/gimme-aws-creds#158]
Recently moved to a new machine and after installing via `pip3 install --upgrade gimme-aws-creds`, I get the error above, when running any `gimme-aws-creds` command.

pip3 list indicates that keyring (20.0.0) is installed.

## Expected Behavior
`gimme-aws-creds --profile prd --register_device` would prompt to register

## Current Behavior
```
Traceback (most recent call last):
  File "/home/chrisd/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/chrisd/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 94, in
load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chrisd/.local/bin/gimme-aws-creds", line 13, in <module>
    from gimme_aws_creds.main import GimmeAWSCreds
  File "/home/chrisd/.local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 32, in <module>
    from .okta import OktaClient
  File "/home/chrisd/.local/lib/python3.6/site-packages/gimme_aws_creds/okta.py", line 21, in <module>
    import keyring
  File "/home/chrisd/.local/lib/python3.6/site-packages/keyring/__init__.py", line 1, in <module>    
    from .core import (
  File "/home/chrisd/.local/lib/python3.6/site-packages/keyring/core.py", line 192, in <module>      
    init_backend()
  File "/home/chrisd/.local/lib/python3.6/site-packages/keyring/core.py", line 96, in init_backend  
    filter(limit, backend.get_all_keyring()),
  File "/home/chrisd/.local/lib/python3.6/site-packages/keyring/util/__init__.py", line 22, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/chrisd/.local/lib/python3.6/site-packages/keyring/backend.py", line 216, in get_all_keyring
    _load_plugins()
  File "/home/chrisd/.local/lib/python3.6/site-packages/keyring/backend.py", line 207, in _load_plugins
    log.exception("Error initializing plugin %s." % ep)
TypeError: not all arguments converted during string formatting
```

## Steps to Reproduce (for bugs)
1. Run any `gimme-aws-creds command`

## Your Environment
* App Version used: 2.2.0
* Environment name and version: Python 3.6
* Operating System and version: WSL (Ubuntu 18.04)

Not sure if this is an environment issue, but thanks for any help!

**Comment by gg-chrisd** [comment]
I've managed to get this working by uninstalling keyring (20.0.0) using:
`sudo -H pip3 uninstall keyring` - Removed from /usr/local/lib/python3.6/dist-packages
`pip3 uninstall keyring` - Removed from ~/.local/...

This reverted keyring to version 10.6.0 in /usr/bin, which seems to be working and I can now register a device and get my creds.

**Comment by jaysgrant** [comment]
I was able to get around this by running
`pip3 install --upgrade keyrings.alt `
as explained here: https://stackoverflow.com/questions/53164278/missing-dependencies-causing-keyring-error-when-opening-spyder3-on-ubuntu18

**Comment by gg-chrisd** [comment]
Apologies for the slow response, that worked, really appreciate the help!

**Comment by Sector95** [comment]
Do we need to bump our base version of keyring in the project?

**Comment by ahummel25** [comment]
I'm getting a similar error using Python 3.8 and 3.7.x

I get this when running `gimme-aws-cred`. Any ideas on a fix?

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keyring/backend.py", line 11, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/gimme-aws-creds", line 13, in <module>
    from gimme_aws_creds.main import GimmeAWSCreds
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 32, in <module>
    from .okta import OktaClient
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 21, in <module>
    import keyring
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keyring/core.py", line 10, in <module>
    from . import backend
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keyring/backend.py", line 13, in <module>
    import importlib_metadata as metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by Sector95** [comment]
Oh, nevermind, this is the WSL.  Yup, correct answer is jaysgrant's response.

**Comment by mjohnson159** [comment]
upgrading keyrings.alt didn't fix anything for me but removing the ~/.local/... keyrings and reinstalling as @gg-chrisd mentioned above fixed it for me

**Comment by ElectricRCAircraftGuy** [comment]
For anyone stumbling here and looking for a generic solution, this worked for me:
```bash
# uninstall and reinstall `keyring` via pip
python3 -m pip uninstall keyring
python3 -m pip install keyring
```
