### ISSUE TITLE
botocore.exceptions.SSLError: SSL validation failed for https://sts.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

### ISSUE THREAD

**Issue by nbvenkata** [Nike-Inc/gimme-aws-creds#163]
I'm getting an error message while I was trying to execute the command "gimme-aws-creds"
(base) C:\Users\nbannagani>gimme-aws-creds
Using password from keyring for nbannagani
Okta Password for nbannagani:
Do you want to save this password in the keyring? (y/n) n
Multi-factor Authentication required.
sms: +1 XXX-XXX-6663 selected
A verification code has been sent to +1 XXX-XXX-6663
Enter verification code: 230159
Detected single role: arn:aws:iam::XXXXXXXXX:role/abcdefghijkl
Traceback (most recent call last):
  File "C:\Users\nbannagani\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\nbannagani\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\nbannagani\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\nbannagani\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\nbannagani\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nbannagani\AppData\Local\Continuum\anaconda3\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\nbannagani\AppData\Local\Continuum\anaconda3\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\nbannagani\AppData\Local\Continuum\anaconda3\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

## Expected Behavior
The output should be created in ~.aws\credentials where you can see access key, secret key and access token.

## Current Behavior
Is there a way where I can turn-off or disable SSL verification?  
Command: gimme-aws-creds with any options to turn off SSL verification.

## Steps to Reproduce (for bugs)
None

## Context

I would appreciate if you could provide any commands that would turn off SSL certificate verification.

## Your Environment
* App Version used:1.0.32912.0
* Environment name and version:
* Operating System and version: Windows 10

**Comment by Sector95** [comment]
I can confidently say that we will not be implementing the ability to disable SSL verification.  Massive security no-no, particularly during credential exchange.
