### ISSUE TITLE
include_path required though it is listed optional

### ISSUE THREAD

**Issue by iniquityx2** [Nike-Inc/gimme-aws-creds#170]
After the v2.3.0 release I'm getting an exception saying KeyError: 'include_path'

This errors goes away when adding that to the config file, however the readme list this as an optional value.  In the same release resolve_aws_alias also became required, but the docs were updated to reflect that.

## Expected Behavior
To not get an exception if include_path is omitted from the config file.

## Current Behavior
You get an exception if it is not included in the config file.

Traceback (most recent call last):
  File "C:\Users\currentuser\AppData\Local\Programs\Python\Python38\Scripts\gimme-aws-creds.cmd", line 47, in <module>
    GimmeAWSCreds().run()
  File "C:\Users\currentuser\AppData\Local\Programs\Python\Python38\lib\site-packages\gimme_aws_creds\main.py", line 466, in run
    self._run()
  File "C:\Users\currentuser\AppData\Local\Programs\Python\Python38\lib\site-packages\gimme_aws_creds\main.py", line 775, in _run
    for data in self.iter_selected_aws_credentials():
  File "C:\Users\currentuser\AppData\Local\Programs\Python\Python38\lib\site-packages\gimme_aws_creds\main.py", line 752, in iter_selected_aws_credentials
    data = self.prepare_data(role, generate_credentials=True)
  File "C:\Users\currentuser\AppData\Local\Programs\Python\Python38\lib\site-packages\gimme_aws_creds\main.py", line 704, in prepare_data
    include_path = self.conf_dict['include_path']
KeyError: 'include_path'

## Possible Solution
Update the readme to reflect it is no longer optional, or implement the default as outlined in the readme, which is set to no

## Steps to Reproduce (for bugs)
Leave the value 'include_path' out of your config file.

## Your Environment

v2.3.0
Python3.8
Windows 10

**Comment by Sector95** [comment]
v2.3.1 is building with a fix for this.  Thanks!
