### ISSUE TITLE
Did not receive SAML Response after successful authentication

### ISSUE THREAD

**Issue by gadupushailaja** [Nike-Inc/gimme-aws-creds#182]
## Expected Behavior
When not in network, I should get a MFA push notification and successful authentication with access to the roles I have permissioned to.

## Current Behavior
I am getting the following error, in my case it is push notification to my phone. I get the below error and after the error is thrown, the push notification sent to my phone. Can someone help here please. I have 2.3.1 latest version.

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gimme-aws-creds", line 17, in 
GimmeAWSCreds().run()
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 466, in run
self._run()
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 775, in _run
for data in self.iter_selected_aws_credentials():
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 751, in iter_selected_aws_credentials
for role in self.aws_selected_roles:
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 651, in aws_selected_roles
selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 642, in aws_roles
self.saml_data['SAMLResponse'],
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 633, in saml_data
self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gimme_aws_creds/okta.py", line 710, in get_saml_response
'Did not receive SAML Response after successful authentication [' + url + ']')
RuntimeError: Did not receive SAML Response after successful authentication

## Steps to Reproduce (for bugs)

1. Get aws keys when MFA enabled with push notification.

## Your Environment

* App Version used: 2.3.1
* Environment name and version: 
* Operating System and version: Mac 10.14.6

**Comment by elijah-roberts** [comment]
@gadupushailaja  I ran in to this issue before when we set a sign on rule that denied mobile access:
![image](https://user-images.githubusercontent.com/19742213/76350922-34fef600-62d2-11ea-8305-8cdc92bca1b1.png)

This application sets the user agent string to `gimme-aws-creds <version>` which gets blocked by the third party mobile(blackberry) block. iOs and Android. appear to be okay. 

Might validate that first, and if it is not that, check for other sign on policies that might be conflicting. You may have to disable them one by one to find the offender, but the error you are seeing is from Okta's side of things...

**Comment by gadupushailaja** [comment]
@elijah-roberts  I checked all the settings in Okta, disabled one by one, but nothing works. Issue is on all the mobile devices. Does MFA push works for you?

**Comment by elijah-roberts** [comment]
yes... what MFA are you using?

**Comment by gadupushailaja** [comment]
Okta Verify - push notification

**Comment by apsylone** [comment]
Same problem here on Okta Verify, push notifications. gimme-aws-creds 2.3.3.

**Comment by apsylone** [comment]
Okay, a little update on my case. I just successfully make it work.
My problem was : I was using a user with an expired password.  
I had to renew my password to make it work again.
Probably the message from SAML or gimme-aws-creds had to be clearer... It would had helped me to save time ahah.

**Comment by gadupushailaja** [comment]
@apsylone  I checked the user, no issues with password, it is working fine for other applications but not with Nike CLI tool :(
