### ISSUE TITLE
Can't make this work on windows

### ISSUE THREAD

**Issue by FenryrMKIII** [Nike-Inc/gimme-aws-creds#203]
I have installed the package using Anaconda. 

I have created a specific environment with Python 3.6 using the following command in Anaconda Prompt : 
`conda create -n aws-cli python=3.6`

pip being already installed this way, I first tried to install the package using 
`pip install --upgrade gimme-aws-creds`

but I ran into a fido package related issue. 
Therefore I had to perform following command : 
`pip install fido2==0.7.0`

before finally installing gimme-aws-creds package succesfully.

Now ... How do I use the program ? I have tried from command line, from python as module, ... Nothing works. Can someone help me make this run on windows in an Anaconda environment ?

**Comment by twoodhouse** [comment]
I'm having the same issue with fido2. I am also on windows.
This is the error message that occurs: 
`Running fido2-0.7.3\setup.py -q bdist_egg --dist-dir C:\Users\TWOODH~1\AppData\Local\Temp\easy_install-szid2l89\fido2-0.7.3\egg-dist-tmp-2f3seakp
Traceback (most recent call last):
  File "C:\Users\twoodhouse\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "C:\Users\twoodhouse\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Users\twoodhouse\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\twoodhouse\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\TWOODH~1\AppData\Local\Temp\easy_install-szid2l89\fido2-0.7.3\setup.py", line 33, in <module>
  File "C:\Users\twoodhouse\AppData\Local\Continuum\anaconda3\lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "C:\Users\twoodhouse\AppData\Local\Continuum\anaconda3\lib\distutils\version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '42.0.2.post20191203'`

**Comment by Sector95** [comment]
This was fixed in the latest version (v2.3.4).
