### ISSUE TITLE
429 Client Error: Too Many Requests for url, error when using sms as authentication

### ISSUE THREAD

**Issue by evgenii-brovkin** [Nike-Inc/gimme-aws-creds#205]
gimme-aws-creds fails to authenticate user **second time** if default authentication method is sms.

## Expected Behavior
Creds obtained after two sms authentiations

## Current Behavior
**gimme-aws-creds fails with following error**
Using password from keyring for Evgenii.Brovkin@nike.com
Multi-factor Authentication required.
sms: XXX XXX-XX-XX selected
A verification code has been sent to XXX XXX-XX-XX
Enter verification code: 045530
Authentication Success! Calling Gimme-Creds Server...
Multi-factor Authentication required.
sms: XXX XXX-XX-XX selected
Traceback (most recent call last):
  File "C:\Users\EBrovk\Miniconda3\envs\nike\Scripts\gimme-aws-creds.cmd", line 47, in <module>
    GimmeAWSCreds().run()
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\main.py", line 466, in run
    self._run()
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\main.py", line 775, in _run
    for data in self.iter_selected_aws_credentials():
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\main.py", line 751, in iter_selected_aws_credentials
    for role in self.aws_selected_roles:
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\main.py", line 651, in aws_selected_roles
    selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\main.py", line 642, in aws_roles
    self.saml_data['SAMLResponse'],
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\main.py", line 633, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\okta.py", line 704, in get_saml_response
    api_response = self.stepup_auth(url, state_token)
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\okta.py", line 121, in stepup_auth
    flow_state.get('stateToken'), flow_state.get('apiResponse'))
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\okta.py", line 305, in _next_login_step
    return self._login_multi_factor(state_token, login_data)
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\okta.py", line 533, in _login_multi_factor
    return self._login_send_sms(state_token, factor)
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\gimme_aws_creds\okta.py", line 363, in _login_send_sms
    response.raise_for_status()
  File "C:\Users\EBrovk\Miniconda3\envs\nike\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://nike.okta.com/api/v1/authn/factors/smsdtvy4qnxcga12N1t7/verify?rememberDevice=True

## Possible Solution
Problem occur because of many requests sent in a short period of time, possible fix would be to set a sleep timer.
The workaround is **manually remove sms as preferred authentication from config file (.okta_aws_login_config) and choose it when prompted to instead.**

## Steps to Reproduce (for bugs)
1. Set preferred authentication method as sms
2. Run the tool
3. Authenticate first time with sms

## Your Environment

* App Version used: 2.3.1
* Environment name and version: Python 3.7
* Operating System and version: Windows 10

**Comment by Sector95** [comment]
This is due to Okta's rate throttling of SMS-type second factors to once every 30 seconds, by my understanding.  I'm not totally sure of a good workaround for this, short of waiting 30 seconds between requests on the first run, but that sounds like a pretty trash user experience.

Any ideas on this?

**Comment by craynafinal** [comment]
I also have a similar issue. I don't get this error for a certain environment but I get this from one particular environment all the time. Any suggestions on how to fix the issue?

**Comment by epierce** [comment]
this is a limitation of the Factors API - SMS/Voice MFA can only be called once every 30 seconds.  If `remember_device` is used, users should not get challenged multiple times during login, so they shouldn't see this error on a regular basis.  If the double challenge is needed, Okta Verify or a WebAuthn factor should be used
