### ISSUE TITLE
webauthn broken

### ISSUE THREAD

**Issue by szechyjs** [Nike-Inc/gimme-aws-creds#228]
## Expected Behavior
Should be able to auth using webauthn. Broke in 2.3.4 release, 2.3.3 works fine.

## Current Behavior
```
Challenge with security keys ...
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds/webauthn.py", line 74, in work
    self._assertions, self._client_data = client.get_assertion(
TypeError: get_assertion() takes 2 positional arguments but 4 were given
```

## Possible Solution
The fido2 library has a breaking change in `0.8.0`, which is why it was pinned back. Either rollback f27b0d531225e33d8b7f2febd322c6c69837c252 or adjust the arguments passed to `get_assertion`.

## Steps to Reproduce (for bugs)
1. MFA with webauthn

## Your Environment
* App Version used: 2.3.4
* Environment name and version: Python 3.8
* Operating System and version: macOS

**Comment by diabg** [comment]
I downgraded fido2 to `0.7.3` and gimme 2.3.4 worked

**Comment by kunickiaj** [comment]
Also worth noting that the upgrade to 0.8.0 of fido2 should make it possible to support PINs fairly easily (#240).

Been working on a patch to fix that as the 0.8.0 API has changed a bit for `get_assertion` but now lets you pass a PIN.

**Comment by kunickiaj** [comment]
> I downgraded fido2 to `0.7.3` and gimme 2.3.4 worked

I'm in favor of @szechyjs fix b/c it opens the doors to fixing #240 as well. It's been quite awhile but no response from the dev team here on either of these issues. Currently resorting to running my own fork.
