### ISSUE TITLE
Getting 403 Client Error: Forbidden for url, although web console works

### ISSUE THREAD

**Issue by mandarin801** [Nike-Inc/gimme-aws-creds#239]
## Expected Behavior
Should get AWS credentials

## Current Behavior
Getting:
    ```Using password from keyring for user@domain.com
    Traceback (most recent call last):
      File "/home/user/anaconda3/bin/gimme-aws-creds", line 17, in <module>
        GimmeAWSCreds().run()
      File "/home/user/anaconda3/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 468, in run
        self._run()
       File "/home/user/anaconda3/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 795, in _run
        for data in self.iter_selected_aws_credentials():
      File "/home/user/anaconda3/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 771, in     iter_selected_aws_credentials
        for role in self.aws_selected_roles:
      File "/home/user/anaconda3/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 671, in aws_selected_roles
        selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
      File "/home/user/anaconda3/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 662, in aws_roles
        self.saml_data['SAMLResponse'],
      File "/home/user/anaconda3/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 653, in saml_data
        self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
      File "/home/user/anaconda3/lib/python3.6/site-packages/gimme_aws_creds/okta.py", line 703, in get_saml_response
        response.raise_for_status()
      File "/home/user/anaconda3/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:     https://domain.okta.com/home/amazon_aws/XXXXXXX/XXX```

## Possible Solution

## Steps to Reproduce (for bugs)

<!-- And so on -->

## Context
Affected two persons on different OS (macOS and Ubuntu) on different versions 2.3.3 and 2.3.4 in different OKTA groups (and different AWS IAM Roles). Logs in OKTA say they are authenticated successfully, but they get this error. Appreciated to any help with it.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* App Version used: 2.3.3 and 2.3.4
* Environment name and version:
* Operating System and version:

**Comment by mandarin801** [comment]
resolved on my side

**Comment by YoniH** [comment]
> resolved on my side

How? I'm having the same issue now

**Comment by mast22** [comment]
Make sure you actually enter the OTP. Symbols do not appear on the console, and I had numpad turned off
