### ISSUE TITLE
webauthn/FIDO2 does not work when a PIN is set

### ISSUE THREAD

**Issue by kunickiaj** [Nike-Inc/gimme-aws-creds#240]
## Expected Behavior
Prompt for U2F PIN

## Current Behavior
MFA fails because U2F key has PIN set

## Possible Solution
Prompt for PIN or way to pass PIN to gimme-aws-creds

## Steps to Reproduce (for bugs)
1. Set a PIN on the FIDO2 portion of your Yubikey (e.g. 5, 5Ci) for example with Yubikey Manager
2. Run gimme-aws-creds

Note, once you set a PIN you can change it but cannot remove it without resetting FIDO2 on the Yubikey which will invalidate any sites you've set up FIDO2/Webauthn using that key.

## Context
Recently set a PIN because it is required for use with Microsoft AAD

```
Multi-factor Authentication required.
webauthn: webauthn selected
Challenge with security keys ...
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/webauthn.py", line 74, in work
    self._assertions, self._client_data = client.get_assertion(
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/fido2/client.py", line 478, in get_assertion
    self._do_get_assertion(
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/fido2/client.py", line 513, in _ctap2_get_assertion
    raise ValueError("PIN required!")
ValueError: PIN required!
Operation timed out or no valid Security Key found !
Traceback (most recent call last):
  File "/Users/<username>/.pyenv/versions/3.8.2/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 468, in run
    self._run()
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 777, in _run
    for data in self.iter_selected_aws_credentials():
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 753, in iter_selected_aws_credentials
    for role in self.aws_selected_roles:
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 653, in aws_selected_roles
    selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 644, in aws_roles
    self.saml_data['SAMLResponse'],
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 635, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 716, in get_saml_response
    api_response = self.stepup_auth(url, state_token)
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 120, in stepup_auth
    flow_state = self._next_login_step(
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 310, in _next_login_step
    return self._check_webauthn_result(state_token, login_data)
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 662, in _check_webauthn_result
    response.raise_for_status()
  File "/Users/<username>/.pyenv/versions/3.8.2/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

## Your Environment
* App Version used: 2.3.4
* Operating System and version: macOS 10.15.6

**Comment by ChristophShyper** [comment]
Thank you so much for solving this problem. 

It was the last place where I needed to use authenticator app.
