### ISSUE TITLE
Unable to authenticate using 2.4.0 and auth device

### ISSUE THREAD

**Issue by pedrodallavc** [Nike-Inc/gimme-aws-creds#284]
## Expected Behavior

Check `Steps to Reproduce`

## Current Behavior
Check `Steps to Reproduce`

## Possible Solution
I checked the `2.3.5` vs. `2.4.0` [comparison](https://github.com/Nike-Inc/gimme-aws-creds/compare/v2.3.5...v2.4.0) and couldn't find anything obvious to fix (sorry).

### Current Behavior (error)
```
$ python --version
Python 3.8.8

$ cat ~/.okta_aws_login_config
[DEFAULT]
okta_org_url = <okta_org_url>
okta_auth_server =
client_id =
gimme_creds_server = appurl
aws_appname = AWS
aws_rolename = all
write_aws_creds = True
cred_profile = role
okta_username = <okta_username>
app_url = <app_url>
resolve_aws_alias = False
preferred_mfa_type = webauthn
remember_device = True
aws_default_duration = 43200
device_token =
output_format = export
include_path = False

$ python -m venv .venv

$ source .venv/bin/activate

$ python -m pip install 'fido2==0.8.1' 'gimme-aws-creds==2.4.0'

$ python
```

```python
>>> from gimme_aws_creds.main import GimmeAWSCreds
>>> from gimme_aws_creds.ui import CLIUserInterface
>>> ui = CLIUserInterface()
>>> aws_creds = GimmeAWSCreds(ui=ui)
>>> list(aws_creds.iter_selected_aws_credentials())

Using password from keyring for **MASKED**
Multi-factor Authentication required.
webauthn: YubiKey 5 selected
Challenge with security keys ...
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/**MASKED**/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/**MASKED**/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/webauthn.py", line 84, in _verify
    self._assertions, self._client_data = client.get_assertion(options, event=self._event,
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/fido2/client.py", line 552, in get_assertion
    self._get_ctap_uv(options.user_verification, pin is not None),
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/fido2/client.py", line 361, in _get_ctap_uv
    raise ClientError.ERR.CONFIGURATION_UNSUPPORTED(
fido2.client.ClientError: (<ERR.CONFIGURATION_UNSUPPORTED: 3>, 'User verification supported but not configured')
Operation timed out or no valid Security Key found !
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 773, in iter_selected_aws_credentials
    for role in self.aws_selected_roles:
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 672, in aws_selected_roles
    selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 663, in aws_roles
    self.saml_data['SAMLResponse'],
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 654, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 647, in aws_app
    self._cache['aws_app'] = aws_app = self._get_selected_app(self.conf_dict.get('aws_appname'), self.aws_results)
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 600, in aws_results
    self.auth_session
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 582, in auth_session
    auth_result = self.okta.auth_session()
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 159, in auth_session
    login_response = self.auth()
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 152, in auth
    flow_state = self._next_login_step(
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 312, in _next_login_step
    return self._check_webauthn_result(state_token, login_data)
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/gimme_aws_creds/okta.py", line 679, in _check_webauthn_result
    response.raise_for_status()
  File "/Users/**MASKED**/.venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: **MASKED**
```

### Expected Behavior (after touching the authenticator device)
```
$ python -m pip install 'fido2==0.8.1' 'gimme-aws-creds<2.4.0'

$ python
```

```python
>>> from gimme_aws_creds.main import GimmeAWSCreds
>>> from gimme_aws_creds.ui import CLIUserInterface
>>> ui = CLIUserInterface()
>>> aws_creds = GimmeAWSCreds(ui=ui)
>>> list(aws_creds.iter_selected_aws_credentials())
Using password from keyring for **MASKED**
Multi-factor Authentication required.
webauthn: webauthn selected
Challenge with security keys ...

Touch your authenticator device now...

[
  {
    "shared_credentials_file": "**MASKED**/.aws/credentials",
    "profile": {
      "name": **MASKED**,
      "derived_name": **MASKED**,
      "config_name": **MASKED**
    },
    "role": {
      "arn": **MASKED**,
      "name": **MASKED**,
      "friendly_name": **MASKED**,
      "friendly_account_name": **MASKED**
    },
    "credentials": {
      "aws_access_key_id": **MASKED**,
      "aws_secret_access_key": **MASKED**,
      "aws_session_token": **MASKED**,
      "aws_security_token": **MASKED**
    }
  }
]
```

## Context

We use this as an internal tool for auth in AWS. Not being able to use this affect daily activities.
The workaround was to downgrade (`2.3.5`)

## Your Environment

* App Version used: `gimme-aws-creds==2.4.0`
* Environment name and version: venv created with Python 3.8.8 
* Operating System and version: macOS BigSur 11.2.2 (20D80)

**Comment by dany74q** [comment]
@pedrodallavc - whoops, my bad ! This happens due to the passing of the user-verification flag
in the get-assertion fido flow.

Turns out passing the uv-flag as `preferred` (as-in, optional verification) - will fail the request if the device does not support it.

Fixed in the proposed PR above.

**Comment by dany74q** [comment]
Hey @pedrodallavc, did 2.4.1 solve this for you ?

**Comment by pedrodallavc** [comment]
@dany74q  Yeap! Thanks a lot :)
