### ISSUE TITLE
Setting up fido authenticator AttributeError: module 'fido2.ctap2' has no attribute 'CAPABILITY'

### ISSUE THREAD

**Issue by reegnz** [Nike-Inc/gimme-aws-creds#286]
## Expected Behavior

I want to register Touch ID with gimme-aws-creds on MacOS

## Current Behavior

```
❯ gimme-aws-creds --action-setup-fido-authenticator


*** Registering a new fido authenticator in Okta.

*** Note that webauthn authenticators must be allowed for this operation to succeed.
*** You may be prompted for MFA more than once for this run.

Using password from keyring for reegnz
Using password from keyring for reegnz
Multi-factor Authentication required.
Pick a factor:
[0] token:software:totp( GOOGLE ) : reegnz@example.com
[1] webauthn: MacBook Touch ID
[2] Okta Verify App: SmartPhone_Android: My Phone Brand
[3] token:software:totp( OKTA ) : reegnz@example.com
Selection: 0
Enter verification code:
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/gimme_aws_creds/main.py", line 469, in run
    self._run()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/gimme_aws_creds/main.py", line 796, in _run
    self.handle_setup_fido_authenticator()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/gimme_aws_creds/main.py", line 896, in handle_setup_fido_authenticator
    credential_id, user = self.okta.setup_fido_authenticator()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/gimme_aws_creds/okta.py", line 919, in setup_fido_authenticator
    credential_id, user_name = self._activate_webauthn_factor(state_token)
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/gimme_aws_creds/okta.py", line 971, in _activate_webauthn_factor
    client_data_json, attestation = webauthn_client.make_credential(user_obj)
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/gimme_aws_creds/webauthn.py", line 100, in make_credential
    self._run_in_thread(self._make_credential, user)
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/gimme_aws_creds/webauthn.py", line 117, in _run_in_thread
    self.locate_device()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/gimme_aws_creds/webauthn.py", line 64, in locate_device
    devs = CtapKeyringDevice.list_devices()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/ctap_keyring_device/ctap_keyring_device.py", line 104, in list_devices
    return [cls()]
  File "/usr/local/Cellar/gimme-aws-creds/2.4.0/libexec/lib/python3.9/site-packages/ctap_keyring_device/ctap_keyring_device.py", line 73, in __init__
    self.capabilities = ctap2.CAPABILITY.CBOR
AttributeError: module 'fido2.ctap2' has no attribute 'CAPABILITY'
```

## Possible Solution

The fido2 dependency is pinned at 0.9.0 in `requirements.txt` that's causing this error.
The latest ctap-keyring-device is trying to use 0.9.1 however.

I propose dropping the upper dependency for transitive dependencies, or pinning to an exact
version of ctap-keyring-device. I think the former one is preferable.

## Steps to Reproduce (for bugs)

See Current Behaviour.

## Context

I want to use MacOS Touch ID with gimme-aws-creds. I cannot do so, even though the feature seems
to have landed with the latest release with #252.

## Your Environment

* App Version used: 2.4.0
* Environment name and version: 
* Operating System and version: MacOS 10.15.7 (19H524)

**Comment by dany74q** [comment]
Hey @reegnz, did 2.4.1 solve this for you ?

**Comment by reegnz** [comment]
Yes!
