### ISSUE TITLE
DUO non web MFA fails with JSON parsing error

### ISSUE THREAD

**Issue by frosforever** [Nike-Inc/gimme-aws-creds#301]
When choosing a non browser DUO MFA, e.g. `push`, the application fails with a JSON parsing error.

```
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/okta.py", line 486, in _login_duo_challenge
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/duo.py", line 120, in trigger_duo
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/duo.py", line 167, in do_auth
  File "/usr/local/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I believe https://github.com/Nike-Inc/gimme-aws-creds/blob/9fd4c4835315413b3104be601ac7e16b81bd0715/gimme_aws_creds/duo.py#L161 expects the response from DUO to be JSON but as of this past Friday it seems to now return html. The required fields, `sid` and `certs_url` are indeed in the returned html. Setting a header of `'Accept': 'application/json'` has no affect and DUO still returns `text/html`.

It is not clear to me if this was changed universally or just for my environment. Are others having this same issue?

## Your Environment
* App Version used: 2.4.1 & 2.3.4
* Operating System and version: macOS 11.4

**Comment by cdolan-coatue** [comment]
@frosforever I am getting a different error but potentially the same manifestation. 

```
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 4, in <module>
    __import__('pkg_resources').run_script('gimme-aws-creds==2.3.4', 'gimme-aws-creds')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/EGG-INFO/scripts/gimme-aws-creds", line 17, in <module>
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 468, in run
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 795, in _run
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 771, in iter_selected_aws_credentials
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 671, in aws_selected_roles
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 662, in aws_roles
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 653, in saml_data
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 646, in aws_app
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 599, in aws_results
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 581, in auth_session
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/okta.py", line 181, in auth_session
  File "/usr/local/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='sid', domain=None, path=None"
```
