### ISSUE TITLE
new issue KeyError: "name='sid', domain=None, path=None"

### ISSUE THREAD

**Issue by jbhasemeier** [Nike-Inc/gimme-aws-creds#309]
## Expected Behavior

gimme-aws-creds has been working nonstop for a long time. i havent changed anything about our user configs. we are still running the same version 2.3.4.

when a user types their okta password when prompted by gimme-aws-creds the process should succeed.

## Current Behavior
the error i am getting when a user types their password in the traceback is: 

KeyError: "name='sid', domain=None, path=None"

```
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 4, in <module>
    __import__('pkg_resources').run_script('gimme-aws-creds==2.3.4', 'gimme-aws-creds')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/EGG-INFO/scripts/gimme-aws-creds", line 17, in <module>
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 468, in run
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 795, in _run
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 771, in iter_selected_aws_credentials
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 671, in aws_selected_roles
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 662, in aws_roles
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 653, in saml_data
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 646, in aws_app
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 599, in aws_results
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/main.py", line 581, in auth_session
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.3.4-py3.8.egg/gimme_aws_creds/okta.py", line 181, in auth_session
  File "/usr/local/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='sid', domain=None, path=None"
```

## Context
this issue was first reported this morning
our users generally use gmme-aws-creds to get their command line aws creds and ssh to instances from there (and various other tasks.)

## Your Environment
OSX Big Sur 11.3.1

**Comment by shivamdixit** [comment]
See https://github.com/Nike-Inc/gimme-aws-creds/issues/302. This is the same issue.

**Comment by jbhasemeier** [comment]
> See #302. This is the same issue.
 thank you closing
