### ISSUE TITLE
Suddenly unable to auth to Okta, okta.py auth_session methods generates KeyError

### ISSUE THREAD

**Issue by achilds-vela** [Nike-Inc/gimme-aws-creds#312]
As of yesterday, I'm suddenly unable to generate credentials using gimme-aws-creds. I'm not sure what the issue is, but currently I'm unable to use the aws cli.

## Expected Behavior

Run gimme aws creds, get credentials, and be on my merry way.

## Current Behavior

When I run gimme-aws-creds, the error I get is a KeyError:
```
...
  File "/Users/achilds/venv-3.9/lib/python3.9/site-packages/gimme_aws_creds/okta.py", line 183, in auth_session
    "session": response.cookies['sid'],
  File "/Users/achilds/venv-3.9/lib/python3.9/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Users/achilds/venv-3.9/lib/python3.9/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='sid', domain=None, path=None"
```

I did some further digging and stored intermediate output and found that gimme-aws-creds' _http_client.get method is actually returning a status_code of 400, which doesn't seem to be caught, and then I assume the next steps are failing on a KeyError because they're expecting to have had a valid response, but that's a guess. The text of that response object is a webpage that just says "400 Bad Request Your request resulted in an error"

## Possible Solution

Frustratingly I cannot find the 400 error in any of Okta's logs, however, I suspect it's something to do with MFA. Or at least, when I look at successful Okta login log messages via gimme-aws-creds, they have an MFA related message, but mine do not. 

## Steps to Reproduce (for bugs)

1. Run gimme-aws-creds via the terminal.

## Your Environment

* App Version used: gimme-aws-creds 2.4.3
* Environment name and version: Ma
* Operating System and version: macOS Big Sur, version 11.4
* Python version:

**Comment by wdolecki-discovery** [comment]
I experience exactly same behavior as above on similar config

- App Version used: gimme-aws-creds 2.4.3 AND 2.4.1
- Environment name and version: Terminal
- Operating System and version: macOS Big Sur, version 11.4
- Python version: Python 3.9.4

**Comment by achilds-vela** [comment]
Well, I found a workaround by changing my `~/.okta_aws_login_config`, but it doesn't match anything in the readme or docs that I can find. Essentially if I add/remove the line `app_url =` from my okta_aws_login_config file, it either works or give the error above. I had a colleague verify that adding/removing this line makes it work or not work (throwing the error above) for him as well

Not working, minimal example :
```
[DEFAULT]
aws_appname = AWS
aws_default_duration = 7200
cred_profile = role
device_token = <SOME_TOKEN>
gimme_creds_server = internal
okta_org_url = <SOME_OKTA_ORG_URL>
okta_username = <SOME_OKTA_USERNAME>
output_format = export
preferred_mfa_type = push
remember_device = True
resolve_aws_alias = False
write_aws_creds = False
```

Working, minimal example :
```
[DEFAULT]
app_url =
aws_appname = AWS
aws_default_duration = 7200
cred_profile = role
device_token = <SOME_TOKEN>
gimme_creds_server = internal
okta_org_url = <SOME_OKTA_ORG_URL>
okta_username = <SOME_OKTA_USERNAME>
output_format = export
preferred_mfa_type = push
remember_device = True
resolve_aws_alias = False
write_aws_creds = False
```

**Comment by DotnetHub** [comment]
I also faced same error - 
```
Traceback (most recent call last):
  .
  .
  .
   File "/home/pritam/.local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 635, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'])
  File "/home/pritam/.local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 628, in aws_app
    self._cache['aws_app'] = aws_app = self._get_selected_app(self.conf_dict.get('aws_appname'), self.aws_results)
  File "/home/pritam/.local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 581, in aws_results
    self.okta.auth_session()
  File "/home/pritam/.local/lib/python3.6/site-packages/gimme_aws_creds/okta.py", line 180, in auth_session
    "session": response.cookies['sid'],
  File "/home/pritam/.local/lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/pritam/.local/lib/python3.6/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='sid', domain=None, path=None"
```

I tried with installing latest gimme-aws-creds version but no luck.

**Comment by datarina** [comment]
I already had `app_url` in my okta config so I tried to update the `gimme-aws-creds`, but it didn't work. After pulling  in the latest versions of `boto3`, `botocore`, and `cryptography` the `gimme-aws-creds` update finally worked, so did the okta auth.
