### ISSUE TITLE
Dockerfile no longer produces a working image

### ISSUE THREAD

**Issue by rosskarchner** [Nike-Inc/gimme-aws-creds#321]
## Expected Behavior

Following the 'Build the docker image locally' instructions in the readme should result in a working gimme-aws-creds command

## Current Behavior

```
~ $ gimme-aws-creds --config
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 4, in <module>
    __import__('pkg_resources').run_script('gimme-aws-creds==2.4.3', 'gimme-aws-creds')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.4.3-py3.8.egg/EGG-INFO/scripts/gimme-aws-creds", line 13, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.4.3-py3.8.egg/gimme_aws_creds/main.py", line 32, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.4.3-py3.8.egg/gimme_aws_creds/okta.py", line 33, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/gimme_aws_creds-2.4.3-py3.8.egg/gimme_aws_creds/u2f.py", line 19, in <module>
  File "/usr/local/lib/python3.8/site-packages/fido2-0.9.2-py3.8.egg/fido2/ctap1.py", line 32, in <module>
    from .cose import ES256
  File "/usr/local/lib/python3.8/site-packages/fido2-0.9.2-py3.8.egg/fido2/cose.py", line 32, in <module>
    from cryptography.hazmat.primitives import hashes, serialization
  File "/usr/local/lib/python3.8/site-packages/cryptography-35.0.0-py3.8-linux-x86_64.egg/cryptography/hazmat/primitives/serialization/__init__.py", line 15, in <module>
    from cryptography.hazmat.primitives.serialization.base import (
  File "/usr/local/lib/python3.8/site-packages/cryptography-35.0.0-py3.8-linux-x86_64.egg/cryptography/hazmat/primitives/serialization/base.py", line 11, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import (
  File "/usr/local/lib/python3.8/site-packages/cryptography-35.0.0-py3.8-linux-x86_64.egg/cryptography/hazmat/primitives/asymmetric/types.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric import (
  File "/usr/local/lib/python3.8/site-packages/cryptography-35.0.0-py3.8-linux-x86_64.egg/cryptography/hazmat/primitives/asymmetric/dsa.py", line 12, in <module>
    from cryptography.hazmat.primitives.asymmetric import (
  File "/usr/local/lib/python3.8/site-packages/cryptography-35.0.0-py3.8-linux-x86_64.egg/cryptography/hazmat/primitives/asymmetric/utils.py", line 6, in <module>
    from cryptography.hazmat.bindings._rust import asn1
ImportError: Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/lib/python3.8/site-packages/cryptography-35.0.0-py3.8-linux-x86_64.egg/cryptography/hazmat/bindings/_rust.abi3.so)
```

## Steps to Reproduce (for bugs)
docker build -t gimme-aws-creds .

1. set up alias as described in README
2. attempt to run command
3. observe ImportError
4.

## Your Environment

* App Version used: latest checkout of master
* Environment name and version:  Docker Desktop 3.5.1
* Operating System and version: Mac OS Mojave

**Comment by chjones** [comment]
@bwynsm Any chance we can get https://github.com/Nike-Inc/gimme-aws-creds/pull/323 merged? The fix works for me.
