### ISSUE TITLE
OKTA based configurations stopped working since this weekend! botocore.exceptions.ProfileNotFound: The config profile () could not be found

### ISSUE THREAD

**Issue by ezrover** [Nike-Inc/gimme-aws-creds#332]
## Current Behavior

Selections (comma separated): 3
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/gimme_aws_creds/main.py", line 469, in run
    self._run()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/gimme_aws_creds/main.py", line 802, in _run
    for data in self.iter_selected_aws_credentials():
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/gimme_aws_creds/main.py", line 774, in iter_selected_aws_credentials
    data = self.prepare_data(role, generate_credentials=True)
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/gimme_aws_creds/main.py", line 698, in prepare_data
    aws_creds = self._get_sts_creds(
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/gimme_aws_creds/main.py", line 210, in _get_sts_creds
    session = boto3.session.Session(profile_name=None)
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/botocore/session.py", line 692, in get_component
    return self._components.get_component(name)
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/botocore/session.py", line 931, in get_component
    self._components[name] = factory()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/botocore/session.py", line 156, in <lambda>
    lambda: create_loader(self.get_config_variable('data_path')))
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/botocore/session.py", line 245, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/botocore/configprovider.py", line 322, in get_config_variable
    return provider.provide()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/botocore/configprovider.py", line 419, in provide
    value = provider.provide()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/botocore/configprovider.py", line 480, in provide
    scoped_config = self._session.get_scoped_config()
  File "/usr/local/Cellar/gimme-aws-creds/2.4.3_1/libexec/lib/python3.10/site-packages/botocore/session.py", line 345, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile () could not be found
% gimme-aws-creds --version                          
gimme-aws-creds 2.4.3

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Unable to select a OKTA based profile

## Your Environment

* App Version used: 2.4.3
* Environment name and version: 
* Operating System and version: 11.6.1

**Comment by ezrover** [comment]
Rebooted the mac and it started working! Bizarre...
