### ISSUE TITLE
Dependency broken to fido2.ctap2 module

### ISSUE THREAD

**Issue by Corpswalker** [Nike-Inc/gimme-aws-creds#355]
Hi,
fido2 was released in version 1.0.0 and it removed AttestedCredentialData from fido2.ctap2 module.

The reference in ctap_keyring_device/ctap_keyring_device.py on line 19 is not available anymore.

Here is the output which led me here:

```
corpswalker@archdev:/usr/bin$ gimme-aws-creds 
Traceback (most recent call last): 
 File "/usr/bin/gimme-aws-creds", line 13, in <module> 
   from gimme_aws_creds.main import GimmeAWSCreds 
 File "/usr/lib/python3.10/site-packages/gimme_aws_creds/main.py", line 32, in <module> 
   from .okta import OktaClient 
 File "/usr/lib/python3.10/site-packages/gimme_aws_creds/okta.py", line 34, in <module> 
   from gimme_aws_creds.webauthn import WebAuthnClient, FakeAssertion 
 File "/usr/lib/python3.10/site-packages/gimme_aws_creds/webauthn.py", line 18, in <module> 
   from ctap_keyring_device.ctap_keyring_device import CtapKeyringDevice 
 File "/usr/lib/python3.10/site-packages/ctap_keyring_device/ctap_keyring_device.py", line 18, in <module> 
   from fido2.ctap2 import ( 
ImportError: cannot import name 'AttestedCredentialData' from 'fido2.ctap2' (/usr/lib/python3.10/site-packages/fido2/ctap2/__init__.py)
```

**Comment by epierce** [comment]
update to requirements merged

**Comment by aanno** [comment]
For me it looks like that simply renaming would not help much. I get errors like this with it:

```bash
$ ./venv/bin/solo1 key verify
Please press the button on your Solo key
Traceback (most recent call last):
  File "/stratis/home/tpasch/dev/scm/github/solo1-cli/./venv/bin/solo1", line 8, in <module>
...
TypeError: Fido2Client.make_credential() got an unexpected keyword argument 'pin'

$ ./venv/bin/solo1 key rng feedkernel
Entropy before: 0x256
Traceback (most recent call last):
  File "/stratis/home/tpasch/dev/scm/github/solo1-cli/./venv/bin/solo1", line 8, in <module>
...
  File "/stratis/home/tpasch/dev/scm/github/solo1-cli/venv/lib/python3.11/site-packages/fido2/hid/__init__.py", line 216, in call
    raise CtapError(struct.unpack_from(">B", recv)[0])
fido2.ctap.CtapError: CTAP error: 0x01 - INVALID_COMMAND
```

Instead, try:

```bash
python3 -m venv .venv
. .venv/bin/activate
pip3 install --force-reinstall -v "fido2==0.9.3" solo1
```
