### ISSUE TITLE
Tests no longer complete on python 3.10.

### ISSUE THREAD

**Issue by zelch** [Nike-Inc/gimme-aws-creds#365]
The nose package is unmaintained.  And as of python 3.10, it simply fails to function.

This results in all tests failing.

## Expected Behavior

Our tests should run.

## Current Behavior

```
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Traceback (most recent call last):
  File "/opt/homebrew/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/opt/homebrew/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/opt/homebrew/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/opt/homebrew/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/opt/homebrew/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/homebrew/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/opt/homebrew/lib/python3.10/site-packages/nose/loader.py", line 354, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/opt/homebrew/lib/python3.10/site-packages/nose/loader.py", line 183, in loadTestsFromDir
    yield self.loadTestsFromName(
  File "/opt/homebrew/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/opt/homebrew/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
    return self.suiteClass(ContextList(tests, context=module))
  File "/opt/homebrew/lib/python3.10/site-packages/nose/suite.py", line 428, in __call__
    return self.makeSuite(tests, context, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/nose/suite.py", line 475, in makeSuite
    suite = self.suiteClass(
  File "/opt/homebrew/lib/python3.10/site-packages/nose/suite.py", line 159, in __init__
    super(ContextSuite, self).__init__(tests)
  File "/opt/homebrew/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/opt/homebrew/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```

## Possible Solution

Retooling to use pytest instead of nosetests.

Sadly, this has gotten tied to another PR because I needed to get tests working in that PR.

## Steps to Reproduce (for bugs)

Install python 3.10.
Attempt to run 'make tests' or 'nosetests -vv tests'.

## Context

It was not possible to complete testing for a PR, because I could not get nosetests to work.

## Your Environment

* App Version used: Current gimme-aws-creds HEAD https://github.com/Nike-Inc/gimme-aws-creds/commit/96064117205a57a0e2850e7eb905070e1024691b
* Operating System and version: MacOS Monterey, Version 12.5.1

**Comment by epierce** [comment]
Fixed in version 2.6.0
