### ISSUE TITLE
--action-configure does not prompt for client_id if gimme_creds_server = appurl

### ISSUE THREAD

**Issue by stargonautone** [Nike-Inc/gimme-aws-creds#404]
When running `gimme-aws-creds --action-configure` on version 2.6.1 and later, setting the `gimme_creds_server` field to the default value of `appurl` causes the configuration wizard to not ask for the `client_id` value which is necessary for authenticating to Okta Identity Engine / OIE. 

It is also not clear whether this default value should be `app_url` since that is the field later prompted for in the configuration wizard.

## Expected Behavior

It is expected that using `appurl` (or `app_url`) for "URL for gimme-creds-server" field would prompt for "Client ID":

```
~ % gimme-aws-creds --action-configure --profile gactest1
If you'd like to assign the Okta configuration to a specific profile
instead of to the default profile, specify the name of the profile.
This is optional.
Okta Configuration Profile Name [gactest1]: 
Enter the Okta URL for your organization. This is https://something.okta[preview].com
Okta URL for your organization: https://[redacted].oktapreview.com
Enter the URL for the gimme-creds-server or 'internal' for handling Okta APIs locally.
URL for gimme-creds-server [appurl]: appurl
Enter the OAuth Client ID for the gimme-aws-creds. This value is REQUIRED for Okta Identity Engine domains. If you do not know this value, contact your Okta admin
Client ID: [redacted]
Enter the application link. This is https://something.okta[preview].com/home/amazon_aws/<app_id>/something
Application url: https://[redacted].oktapreview.com/home/amazon_aws/[redacted]/[redacted]
Do you want to write the temporary AWS to ~/.aws/credentials?
If no, the credentials will be written to stdout.
Please answer y or n.
Write AWS Credentials [n]: y
Do you want to resolve aws account id to aws alias ?
Please answer y or n.
Resolve AWS alias [n]: y
Do you want to include full role path to the role name in AWS credential profile name?
Please answer y or n.
Include Path [n]: y
Enter the ARN for the AWS role you want credentials for. 'all' will retrieve all roles.
This is optional, you can select the role when you run the CLI.
AWS Role ARN: 
If you'd like to set your okta username in the config file, specify the username
.This is optional.
Okta User Name: 
If you'd like to set the default session duration, specify it (in seconds).
This is optional.
AWS Default Session Duration [3600]:     
If you'd like to set a preferred device type to use for MFA, enter it here.
This is optional. valid devices types:

            - push - Okta Verify App push or DUO push (depends on okta supplied provider type)
            - token:software:totp - OTP using the Okta Verify App
            - token:hardware - OTP using hardware like Yubikey
            - call - OTP via Voice call
            - sms - OTP via SMS message
            - web - DUO uses localhost webbrowser to support push|call|passcode
            - passcode - DUO uses `OKTA_MFA_CODE` or `--mfa-code` if set, or prompts user for passcode(OTP).
            
Preferred MFA Device Type: 
Do you want the MFA device be remembered?
Please answer y or n.
Remember device [n]: y
The AWS credential profile defines which profile is used to store the temp AWS creds.
If set to 'role' then a new profile will be created matching the role name assumed by the user.
If set to 'acc-role' then a new profile will be created matching the role name assumed by the user, but prefixed with account number to avoid collisions.
If set to 'default' then the temp creds will be stored in the default profile
If set to any other value, the name of the profile will match that value.
AWS Credential Profile [role]: gactest1
```

### "Client ID" is not prompted if "URL for gimme-creds-server [appurl]" is set to default "appurl" value:

```
~ % gimme-aws-creds --action-configure --profile gactest2
If you'd like to assign the Okta configuration to a specific profile
instead of to the default profile, specify the name of the profile.
This is optional.
Okta Configuration Profile Name [gactest2]: 
Enter the Okta URL for your organization. This is https://something.okta[preview].com
Okta URL for your organization: https://[redacted].oktapreview.com
Enter the URL for the gimme-creds-server or 'internal' for handling Okta APIs locally.
URL for gimme-creds-server [appurl]: appurl
Enter the application link. This is https://something.okta[preview].com/home/amazon_aws/<app_id>/something
Application url: https://[redacted].oktapreview.com/home/amazon_aws/[redacted]/[redacted]
Do you want to write the temporary AWS to ~/.aws/credentials?
If no, the credentials will be written to stdout.
Please answer y or n.
Write AWS Credentials [n]: y
Do you want to resolve aws account id to aws alias ?
Please answer y or n.
Resolve AWS alias [n]: y
Do you want to include full role path to the role name in AWS credential profile name?
Please answer y or n.
Include Path [n]: y
Enter the ARN for the AWS role you want credentials for. 'all' will retrieve all roles.
This is optional, you can select the role when you run the CLI.
AWS Role ARN: 
If you'd like to set your okta username in the config file, specify the username
.This is optional.
Okta User Name: 
If you'd like to set the default session duration, specify it (in seconds).
This is optional.
AWS Default Session Duration [3600]:     
If you'd like to set a preferred device type to use for MFA, enter it here.
This is optional. valid devices types:

            - push - Okta Verify App push or DUO push (depends on okta supplied provider type)
            - token:software:totp - OTP using the Okta Verify App
            - token:hardware - OTP using hardware like Yubikey
            - call - OTP via Voice call
            - sms - OTP via SMS message
            - web - DUO uses localhost webbrowser to support push|call|passcode
            - passcode - DUO uses `OKTA_MFA_CODE` or `--mfa-code` if set, or prompts user for passcode(OTP).
            
Preferred MFA Device Type: 
Do you want the MFA device be remembered?
Please answer y or n.
Remember device [n]: y
The AWS credential profile defines which profile is used to store the temp AWS creds.
If set to 'role' then a new profile will be created matching the role name assumed by the user.
If set to 'acc-role' then a new profile will be created matching the role name assumed by the user, but prefixed with account number to avoid collisions.
If set to 'default' then the temp creds will be stored in the default profile
If set to any other value, the name of the profile will match that value.
AWS Credential Profile [role]: gactest2
```

### This issue is bypassed if the URL of the AWS application is used for "URL for gimme-creds-server":

```
~ % gimme-aws-creds --action-configure --profile gactest3
If you'd like to assign the Okta configuration to a specific profile
instead of to the default profile, specify the name of the profile.
This is optional.
Okta Configuration Profile Name [gactest3]: 
Enter the Okta URL for your organization. This is https://something.okta[preview].com
Okta URL for your organization: https://[redacted].oktapreview.com
Enter the URL for the gimme-creds-server or 'internal' for handling Okta APIs locally.
URL for gimme-creds-server [appurl]: https://[redacted].oktapreview.com/home/amazon_aws/[redacted]/[redacted]
Enter the OAuth Client ID for the gimme-aws-creds. This value is REQUIRED for Okta Identity Engine domains. If you do not know this value, contact your Okta admin
Client ID: [redacted]
Enter the OAuth authorization server for the gimme-creds-server. If you do not know this value, contact your Okta admin
Authorization server: https://[redacted].oktapreview.com
Do you want to write the temporary AWS to ~/.aws/credentials?
If no, the credentials will be written to stdout.
Please answer y or n.
Write AWS Credentials [n]: y
Enter the AWS Okta App Name.
This is optional, you can select the App when you run the CLI.
AWS App Name: 
Do you want to resolve aws account id to aws alias ?
Please answer y or n.
Resolve AWS alias [n]: y
Do you want to include full role path to the role name in AWS credential profile name?
Please answer y or n.
Include Path [n]: y
Enter the ARN for the AWS role you want credentials for. 'all' will retrieve all roles.
This is optional, you can select the role when you run the CLI.
AWS Role ARN: 
If you'd like to set your okta username in the config file, specify the username
.This is optional.
Okta User Name: 
If you'd like to set the default session duration, specify it (in seconds).
This is optional.
AWS Default Session Duration [3600]: 3600
If you'd like to set a preferred device type to use for MFA, enter it here.
This is optional. valid devices types:

            - push - Okta Verify App push or DUO push (depends on okta supplied provider type)
            - token:software:totp - OTP using the Okta Verify App
            - token:hardware - OTP using hardware like Yubikey
            - call - OTP via Voice call
            - sms - OTP via SMS message
            - web - DUO uses localhost webbrowser to support push|call|passcode
            - passcode - DUO uses `OKTA_MFA_CODE` or `--mfa-code` if set, or prompts user for passcode(OTP).
            
Preferred MFA Device Type: 
Do you want the MFA device be remembered?
Please answer y or n.
Remember device [n]: y
The AWS credential profile defines which profile is used to store the temp AWS creds.
If set to 'role' then a new profile will be created matching the role name assumed by the user.
If set to 'acc-role' then a new profile will be created matching the role name assumed by the user, but prefixed with account number to avoid collisions.
If set to 'default' then the temp creds will be stored in the default profile
If set to any other value, the name of the profile will match that value.
AWS Credential Profile [role]: gactest3
```

## Possible Solution

Prompt for "Client ID" on --action-configure configuration wizard (or if OIE is detected)

## Steps to Reproduce (for bugs)

1. `gimme-aws-creds --action-configure`
2. Test with "URL for gimme-creds-server" set to default `appurl` value or URL of AWS app in Okta
3. Verify "Client ID" is not prompted if using default `appurl` value

## Context

Having this resolved would reduce support requests where authentication does not work because user did not populate `client_id` in the configuration.

## Your Environment

* App Version used: 2.6.1, 2.6.2
* Environment name and version: n/a 
* Operating System and version: macOS 13, Windows

**Comment by stargonautone** [comment]
It looks like having the AWS app URL as the `gimme_creds_server` results in an app authorization error resulting in no JSON being returned due to this being an unsupported value, so perhaps this should instead be resolved by having the configuration wizard prompt for `client_id` if the default `appurl` value is selected or by making another supported selection available. 

When connecting with my "gactest3" example above, I get the following JSONDecodeError: 

```
~ % gimme-aws-creds -p oie1-dev3 --open-browser
The system web browser will open the following URL to begin Okta device authorization:

https://[redacted].oktapreview.com/activate?user_code=[redacted]

Authentication Success! Calling Gimme-Creds Server...
Traceback (most recent call last):
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 475, in run
    self._run()
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 861, in _run
    for data in self.iter_selected_aws_credentials():
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 831, in iter_selected_aws_credentials
    aws_results = executor.map(generate_credentials_prepare_data, self.aws_selected_roles)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 723, in aws_selected_roles
    selected_roles = self._get_selected_roles(self.requested_roles, self.aws_roles)
                                                                    ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 714, in aws_roles
    self.saml_data['SAMLResponse'],
    ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 705, in saml_data
    self._cache['saml_data'] = saml_data = self.okta.get_saml_response(self.aws_app['links']['appLink'], self.auth_session)
                                                                       ^^^^^^^^^^^^
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 698, in aws_app
    self._cache['aws_app'] = aws_app = self._get_selected_app(self.conf_dict.get('aws_appname'), self.aws_results)
                                                                                                 ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 689, in aws_results
    aws_results = self._call_gimme_creds_server(self.okta, self.gimme_creds_server)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/gimme_aws_creds/main.py", line 238, in _call_gimme_creds_server
    if not response.json():
           ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/gimme-aws-creds/2.6.1/libexec/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
````

**Comment by epierce** [comment]
Please try the version that was just committed in the dev branch (`pip3 install --upgrade https://github.com/Nike-Inc/gimme-aws-creds/archive/dev.zip`) and let me know if it works for you.

**Comment by stargonautone** [comment]
Issue persists on dev branch 2.6.2, I am not prompted to enter OIDC App Client ID when using `appurl` for "URL for gimme-creds-server": 

```
bin % gimme-aws-creds --action-configure
If you'd like to assign the Okta configuration to a specific profile
instead of to the default profile, specify the name of the profile.
This is optional.
Okta Configuration Profile Name [DEFAULT]: gactest4
Enter the Okta URL for your organization. This is https://something.okta[preview].com
Okta URL for your organization: https://[redatcted].oktapreview.com
Enter the URL for the gimme-creds-server or 'internal' for handling Okta APIs locally.
URL for gimme-creds-server [appurl]: appurl
Enter the application link. This is https://something.okta[preview].com/home/amazon_aws/<app_id>/something
Application url: https://[redacted].oktapreview.com/home/amazon_aws/[redatcted]/[redatcted]
Do you want to write the temporary AWS to ~/.aws/credentials?
If no, the credentials will be written to stdout.
Please answer y or n.
Write AWS Credentials [n]: y
Do you want to resolve aws account id to aws alias ?
Please answer y or n.
Resolve AWS alias [n]: y
Do you want to include full role path to the role name in AWS credential profile name?
Please answer y or n.
Include Path [n]: y
Enter the ARN for the AWS role you want credentials for. 'all' will retrieve all roles.
This is optional, you can select the role when you run the CLI.
AWS Role ARN: 
If you'd like to set your okta username in the config file, specify the username
.This is optional.
Okta User Name: 
If you'd like to set the default session duration, specify it (in seconds).
This is optional.
AWS Default Session Duration [3600]: 3600
If you'd like to set a preferred device type to use for MFA, enter it here.
This is optional. valid devices types:

            - push - Okta Verify App push or DUO push (depends on okta supplied provider type)
            - token:software:totp - OTP using the Okta Verify App
            - token:hardware - OTP using hardware like Yubikey
            - call - OTP via Voice call
            - sms - OTP via SMS message
            - web - DUO uses localhost webbrowser to support push|call|passcode
            - passcode - DUO uses `OKTA_MFA_CODE` or `--mfa-code` if set, or prompts user for passcode(OTP).
            
Preferred MFA Device Type: 
Do you want the MFA device be remembered?
Please answer y or n.
Remember device [n]: y
The AWS credential profile defines which profile is used to store the temp AWS creds.
If set to 'role' then a new profile will be created matching the role name assumed by the user.
If set to 'acc-role' then a new profile will be created matching the role name assumed by the user, but prefixed with account number to avoid collisions.
If set to 'default' then the temp creds will be stored in the default profile
If set to any other value, the name of the profile will match that value.
AWS Credential Profile [role]: gactest4
```

**Comment by epierce** [comment]
These changes will be included in the next release
