### ISSUE TITLE
gimme-aws-creds command throw the error

### ISSUE THREAD

**Issue by pramilkprince** [Nike-Inc/gimme-aws-creds#442]
Getting error on executing commands "gimme-aws-creds" or  "gimme-aws-creds --config" or gimme-aws-creds --register-device on windows10 machine. The error is thrown as follows

C:\Windows\System32>gimme-aws-creds
Traceback (most recent call last):
  File ".......................\AppData\Local\Programs\Python\Python311\Scripts\gimme-aws-creds.cmd", line 47, in <module>
    GimmeAWSCreds().run()
  File ".......................\AppData\Local\Programs\Python\Python311\Lib\site-packages\gimme_aws_creds\main.py", line 466, in run
    self._run()
  File ".......................\AppData\Local\Programs\Python\Python311\Lib\site-packages\gimme_aws_creds\main.py", line 769, in _run
    self.handle_action_configure()
  File ".......................\AppData\Local\Programs\Python\Python311\Lib\site-packages\gimme_aws_creds\main.py", line 798, in handle_action_configure
    if not self.config.action_configure:
           ^^^^^^^^^^^
  File ".......................\AppData\Local\Programs\Python\Python311\Lib\site-packages\gimme_aws_creds\main.py", line 489, in config
    self.resolver = self.get_resolver()
                    ^^^^^^^^^^^^^^^^^^^
  File ".......................\AppData\Local\Programs\Python\Python311\Lib\site-packages\gimme_aws_creds\main.py", line 555, in get_resolver
    return AwsResolver(self.config.verify_ssl_certs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".......................\AppData\Local\Programs\Python\Python311\Lib\site-packages\gimme_aws_creds\aws.py", line 41, in __init__
    retries = Retry(total=5, backoff_factor=1,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist'

Python packages installed as follows
C:\Windows\System32>pip list
Package            Version
------------------ ----------
beautifulsoup4     4.12.2
boto3              1.33.9
botocore           1.33.9
certifi            2023.11.17
cffi               1.16.0
charset-normalizer 3.3.2
configparser       3.8.1
cryptography       41.0.7
fido2              0.7.3
gimme-aws-creds    2.3.1
idna               3.6
importlib-metadata 7.0.0
jaraco.classes     3.3.0
jmespath           1.0.1
keyring            24.3.0
more-itertools     10.1.0
okta               0.0.4
pip                23.3.1
podman-compose     1.0.6
pycparser          2.21
python-dateutil    2.8.0
python-dotenv      1.0.0
pywin32-ctypes     0.2.2
PyYAML             6.0.1
requests           2.31.0
s3transfer         0.8.2
setuptools         65.5.0
six                1.16.0
soupsieve          2.5
urllib3            2.0.7
zipp               3.17.0

Can you please help to get rid off this error?

**Comment by pramilkprince** [comment]
This issue got resolved by replacing installed version of urllib3 with urllib3==1.25.11
