### ISSUE TITLE
KeyError: 'idp_entry_url'

### ISSUE THREAD

**Issue by talsch** [Nike-Inc/gimme-aws-creds#6]
Hi,
I am trying to use your tool
and getting the following error:

Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 4, in <module>
    __import__('pkg_resources').run_script('gimme-aws-creds==0.1.3', 'gimme-aws-creds')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds-0.1.3-py3.6.egg/EGG-INFO/scripts/gimme-aws-creds", line 175, in <module>
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds-0.1.3-py3.6.egg/EGG-INFO/scripts/gimme-aws-creds", line 107, in run
KeyError: 'idp_entry_url'

Is this tool  a wrapper for the Okta aws cli tool (which I found very problematic) which means I need the cli tool working first, or replaces it completely?

Thanks,
Tal

**Comment by anners** [comment]
Hi Tal,

This is not a wrapper for the Okta AWS cli tool. 

Did you run gimme-aws-creds --configure? This should create ~/.okta_aws_login_config with your idp_entry_url.

**Comment by talsch** [comment]
Hi,
Yes I did...
Tried several of the options.
The idp_entry_url is set.

**Comment by anners** [comment]
A KeyError generally means the key doesn't exist. If the idp_entry_url is set in your ~/.okta_aws_login_config, can you verify that the user who is running gimme-aws-creds has read permissions to .okta_aws_login_config? I was able to duplicate your error when I set the permissions on .okta_aws_login_config to 000.
