### ISSUE TITLE
Using gimme-aws-creds without a section for a profile errors out

### ISSUE THREAD

**Issue by roboweaver** [Nike-Inc/gimme-aws-creds#62]
I reinstalled the latest version of gimme-aws-creds and found that there are some odd error conditions that I couldn't get around until I manually added a section to my ~/.aws/credentials that was:

```
[cloud-admin]
aws_access_key_id = 
aws_secret_access_key = 
```

When the section was missing I got this:

```
RobWeaver:.aws robweaver$ gimme-aws-creds --version
gimme-aws-creds 1.0.13
RobWeaver:.aws robweaver$ gimme-aws-creds
Using password from keyring for robweaver
Multi-factor Authentication required.
Pick a factor:
[ 0 ] token:software:totp( GOOGLE ) : robweaver@workfront.com
Unknown MFA type: web
[ 2 ] sms: +1 XXX-XXX-4762
Selection: 0
Enter verification code: 618167
Authentication Success! Getting AWS Accounts
Pick a role:
[0] arn:aws:iam::252989011795:role/cloud-admin
Selection: 0
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 433, in run
    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, config.aws_default_duration)
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 133, in _get_sts_creds
    client = boto3.client('sts')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 850, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 474, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1662, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1213, in load
    return self._load_creds_via_assume_role(self._profile_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1219, in _load_creds_via_assume_role
    role_config = self._get_role_config(profile_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1297, in _get_role_config
    self._validate_source_profile(profile_name, source_profile)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1328, in _validate_source_profile
    source_profile_name, parent_profile_name)
botocore.exceptions.InvalidConfigError: The source_profile "cloud-admin" referenced in the profile "default" does not exist.
```

When I add the section without the empty values, I get:

```
RobWeaver:.aws robweaver$ gimme-aws-creds
Using password from keyring for robweaver
Multi-factor Authentication required.
Pick a factor:
[ 0 ] token:software:totp( GOOGLE ) : robweaver@workfront.com
Unknown MFA type: web
[ 2 ] sms: +1 XXX-XXX-4762
Selection: 0
Enter verification code: 094751
Authentication Success! Getting AWS Accounts
Pick a role:
[0] arn:aws:iam::252989011795:role/cloud-admin
Selection: 0
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 433, in run
    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, config.aws_default_duration)
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 133, in _get_sts_creds
    client = boto3.client('sts')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 850, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 474, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1662, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1213, in load
    return self._load_creds_via_assume_role(self._profile_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1219, in _load_creds_via_assume_role
    role_config = self._get_role_config(profile_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1297, in _get_role_config
    self._validate_source_profile(profile_name, source_profile)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1340, in _validate_source_profile
    source_profile_name)
botocore.exceptions.InvalidConfigError: The source_profile "cloud-admin" must specify either static credentials or an assume role configuration
```
And finally when I add the key id part:

```
RobWeaver:.aws robweaver$ gimme-aws-creds
Using password from keyring for robweaver
Multi-factor Authentication required.
Pick a factor:
[ 0 ] token:software:totp( GOOGLE ) : robweaver@workfront.com
Unknown MFA type: web
[ 2 ] sms: +1 XXX-XXX-4762
Selection: 0
Enter verification code: 348592
Authentication Success! Getting AWS Accounts
Pick a role:
[0] arn:aws:iam::252989011795:role/cloud-admin
Selection: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1396, in _resolve_static_credentials_from_profile
    secret_key=profile['aws_secret_access_key'],
KeyError: 'aws_secret_access_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 433, in run
    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, config.aws_default_duration)
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 133, in _get_sts_creds
    client = boto3.client('sts')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 850, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 474, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1662, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1213, in load
    return self._load_creds_via_assume_role(self._profile_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1221, in _load_creds_via_assume_role
    role_config, profile_name
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1381, in _resolve_source_credentials
    return self._resolve_credentials_from_profile(source_profile)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1388, in _resolve_credentials_from_profile
    return self._resolve_static_credentials_from_profile(profile)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1401, in _resolve_static_credentials_from_profile
    provider=self.METHOD, cred_var=str(e))
botocore.exceptions.PartialCredentialsError: Partial credentials found in assume-role, missing: 'aws_secret_access_key'
```
And when I add the last line for the secret:

```
RobWeaver:.aws robweaver$ gimme-aws-creds
Using password from keyring for robweaver
Multi-factor Authentication required.
Pick a factor:
[ 0 ] token:software:totp( GOOGLE ) : robweaver@workfront.com
Unknown MFA type: web
[ 2 ] sms: +1 XXX-XXX-4762
Selection: 0
Enter verification code: 004090
Authentication Success! Getting AWS Accounts
Pick a role:
[0] arn:aws:iam::252989011795:role/cloud-admin
Selection: 0
writing role arn:aws:iam::252989011795:role/cloud-admin to /Users/robweaver/.aws/credentials
```

**Comment by epierce** [comment]
Do you have anything special in `~/.aws/config`? It looks Boto doesn't like the fact that the "cloud-admin" profile is referenced in there before it has been creaetd in the credentials file.

**Comment by roboweaver** [comment]
the ~/.aws/config file has the profile mapping like 

```
[profile wf-web]
source_profile = cloud-admin
role_arn = arn:aws:iam::xxxxxxxxx:role/admin
```

there is no profile "cloud-admin" since it is only used to assume roles.

Note that if I remove the ~/.aws/credentials file, I also don't error out.

```
RobWeaver:.aws robweaver$ gimme-aws-creds --config
If you'd like to assign the Okta configuration to a specific profile
instead of to the default profile, specify the name of the profile.
This is optional.
Okta Configuration Profile Name [DEFAULT]: 
Enter the Okta URL for your organization. This is https://something.okta[preview].com
Okta URL for your organization [https://workfront.okta.com]: 
Enter the URL for the gimme-creds-server or 'internal' for handling Okta APIs locally.
URL for gimme-creds-server [appurl]: 
Enter the application link. This is https://something.okta[preview].com/home/amazon_aws/<app_id>/something
Application url [https://workfront.okta.com/home/amazon_aws/0oayn19za99iEjE4N2p6/272?fromHome=true]: 
Do you want to write the temporary AWS to ~/.aws/credentials?
If no, the credentials will be written to stdout.
Please answer y or n.
Write AWS Credentials [n]: y
Do you want to resolve aws account id to aws alias ?
Please answer y or n.
Resolve AWS alias [n]: 
Enter the ARN for the AWS role you want credentials for. 'ALL' will retrieve all roles.
This is optional, you can select the role when you run the CLI.
AWS Role ARN: 
If you'd like to set your okta username in the config file, specify the username
.This is optional.
Okta User Name [robweaver]: 
If you'd like to set the default session duration, specify it (in seconds).
This is optional.
AWS Default Session Duration [43200]: 
If you'd like to set a preferred device type to use for MFA, enter it here.
This is optional. valid devices types:[sms, call, push, token, token:software:totp]
Preferred MFA Device Type: 
The AWS credential profile defines which profile is used to store the temp AWS creds.
If set to 'role' then a new profile will be created matching the role name assumed by the user.
If set to 'default' then the temp creds will be stored in the default profile
If set to any other value, the name of the profile will match that value.
AWS Credential Profile [role]: 
RobWeaver:.aws robweaver$ 
```

**Comment by roboweaver** [comment]
Ran into this again with a user who had no `~/.aws/credentials` file in place. 

Created the dummy file as shown in my initial comments and it did allow him to work. 

I think either gimme-aws-creds should create the file when it is missing, or give an error for that condition with reference to the file format that will fix the problem.

**Comment by Sector95** [comment]
Asked a follow-up question in #63

**Comment by erikeckhardt** [comment]
while experimenting with how to get Terraform to work with a profile other than the default, I stupidly deleted my `~/.aws/credentials` file thinking I could reset some stuff and start over easily.

Yeah, no.

I still haven't solved the problem after more than a couple hours of struggling. Can some attention be given to this, please, so that people who delete what seems like a simple config file aren't suddenly broken with no easy way to recover?

```
$ gimme-aws-creds --profile myProfile
Using password from keyring for first.last
Password for first.last: 
Do you want to save this password in the keyring? (y/n) n
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 465, in run
    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, config.aws_default_duration)
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 136, in _get_sts_creds
    client = boto3.client('sts')
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 80, in _get_default_session
    setup_default_session()
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 34, in setup_default_session
    DEFAULT_SESSION = Session(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 680, in get_component
    return self._components.get_component(name)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 903, in get_component
    self._components[name] = factory()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 150, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 234, in get_config_variable
    logical_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/configprovider.py", line 227, in get_config_variable
    return provider.provide()
  File "/usr/local/lib/python3.7/site-packages/botocore/configprovider.py", line 324, in provide
    value = provider.provide()
  File "/usr/local/lib/python3.7/site-packages/botocore/configprovider.py", line 383, in provide
    config = self._session.get_scoped_config()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 335, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (/Users/first.last/.aws/credentials) could not be found
```
