### ISSUE TITLE
gimme-aws-creds v1.1.0 runtime error after picking role

### ISSUE THREAD

**Issue by maxchisto** [Nike-Inc/gimme-aws-creds#78]
```
~ $ gimme-aws-creds
Using password from keyring for maxim.chistokletov@nike.com
Multi-factor Authentication required.
Pick a factor:
[ 0 ] token:software:totp( GOOGLE ) : Maxim.Chistokletov@nike.com
[ 1 ] sms: +1 XXX-XXX-0000
Selection: 0
Enter verification code: 382471
Authentication Success! Calling Gimme-Creds Server...
Pick an app:
[0] CDT-NPlus-Prod (*redacted*)
[1] CDT-NPlus-Test (*redacted*)
Selection: 0
Pick a role:
[0] arn:aws:iam::*redacted*:role/OktaPoweruserRole
[1] arn:aws:iam::*redacted*:role/OktaReadonlyRole
Selection: 1
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 453, in run
    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, config.aws_default_duration)
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds/main.py", line 135, in _get_sts_creds
    client = boto3.client('sts')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 80, in _get_default_session
    setup_default_session()
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 34, in setup_default_session
    DEFAULT_SESSION = Session(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 729, in get_component
    return self._components.get_component(name)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 946, in get_component
    self._components[name] = factory()
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 186, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 281, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 308, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 385, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (DEFAULT) could not be found
```

.okta_aws_login_config:
```
[DEFAULT]
okta_org_url = https://nike.okta.com
okta_auth_server = *redacted*
client_id = *redacted*
gimme_creds_server = https://api.sec.nikecloud.com/gimmecreds/accounts
aws_appname = 
aws_rolename = 
write_aws_creds = True
cred_profile = default
okta_username = maxim.chistokletov@nike.com
app_url = 
resolve_aws_alias = False
preferred_mfa_type = 
aws_default_duration = 3600
device_token = *redacted*
```

`.aws/` hasn't been created yet

**Comment by maxchisto** [comment]
Made it work by copying `.okta_aws_login_config` from someone who got it working.
