### ISSUE TITLE
Invalid URL No schema supplied

### ISSUE THREAD

**Issue by samuel-72** [Nike-Inc/gimme-aws-creds#9]
I get the below error while trying to run the script:

```
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 4, in <module>
    __import__('pkg_resources').run_script('gimme-aws-creds==0.1.3', 'gimme-aws-creds')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds-0.1.3-py3.6.egg/EGG-INFO/scripts/gimme-aws-creds", line 175, in <module>
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds-0.1.3-py3.6.egg/EGG-INFO/scripts/gimme-aws-creds", line 113, in run
  File "/usr/local/lib/python3.6/site-packages/gimme_aws_creds-0.1.3-py3.6.egg/gimme_aws_creds/config.py", line 97, in get_okta_api_key
  File "/usr/local/lib/python3.6/site-packages/cerberus_python_client-0.3-py3.6.egg/cerberus/client.py", line 39, in __init__
  File "/usr/local/lib/python3.6/site-packages/cerberus_python_client-0.3-py3.6.egg/cerberus/client.py", line 47, in set_token
  File "/usr/local/lib/python3.6/site-packages/cerberus_python_client-0.3-py3.6.egg/cerberus/user_auth.py", line 40, in get_token
  File "/usr/local/lib/python3.6/site-packages/cerberus_python_client-0.3-py3.6.egg/cerberus/user_auth.py", line 31, in get_auth
  File "/usr/local/lib/python3.6/site-packages/requests-2.14.2-py3.6.egg/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.14.2-py3.6.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.14.2-py3.6.egg/requests/sessions.py", line 504, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/site-packages/requests-2.14.2-py3.6.egg/requests/sessions.py", line 436, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/site-packages/requests-2.14.2-py3.6.egg/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/site-packages/requests-2.14.2-py3.6.egg/requests/models.py", line 382, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/v2/auth/user': No schema supplied. Perhaps you meant http:///v2/auth/user?
```

Given below is how my config file looks:

[DEFAULT]
idp_entry_url = <url>
write_aws_creds = True
cred_profile = default
aws_appname = ''
aws_rolename = ''
cerberus_url = 

Could you kindly let me know what is going wrong. Thanks.

**Comment by anners** [comment]
Hi,

You need to supply your Okta idp_entry_url - This is your Okta entry url, which is typically something like https://companyname.okta.com.

Let me know if that fixes the issue.

**Comment by samuel-72** [comment]
Hi,

  No, I still get the same error.

**Comment by anners** [comment]
Hi - the error is coming from cerberus.client, if you aren't using cerberus you will need to set your  OKTA_API_KEY environment variable.

**Comment by SectorNine50** [comment]
Added some error-handling to make the problem more clear to the end-user.  Can be found in the `conf-profile` branch.
