### ISSUE TITLE
Error while executing gimme-aws-creds

### ISSUE THREAD

**Issue by geetchoubey** [Nike-Inc/gimme-aws-creds#93]
I am using Ubuntu 16.04 with Python3.
After running `gimme-aws-creds` , I am prompted for password and after which the verification code is sent to my number but right after that I am getting the following issue.
What could be the problem behind this?

```
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 4, in <module>
    __import__('pkg_resources').run_script('gimme-aws-creds==1.1.1', 'gimme-aws-creds')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/gimme_aws_creds-1.1.1-py3.5.egg/EGG-INFO/scripts/gimme-aws-creds", line 17, in <module>
  File "/usr/local/lib/python3.5/dist-packages/gimme_aws_creds-1.1.1-py3.5.egg/gimme_aws_creds/main.py", line 442, in run
 File "/usr/local/lib/python3.5/dist-packages/gimme_aws_creds-1.1.1-py3.5.egg/gimme_aws_creds/okta.py", line 448, in get_saml_response
  File "/usr/local/lib/python3.5/dist-packages/gimme_aws_creds-1.1.1-py3.5.egg/gimme_aws_creds/okta.py", line 97, in stepup_auth
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dshefchik** [comment]
Any update on this?

**Comment by geetchoubey** [comment]
@dshefchik I changed the auth mode to Push type and it worked

**Comment by Sector95** [comment]
Are you still getting this issue on the latest version?
